# Generated by Django 5.2 on 2026-03-15 14:09

import apps.pharmacies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la pharmacie')),
                ('numero_agrement', models.CharField(blank=True, default='', help_text="Numéro d'agrément délivré par le Ministère de la Santé du Bénin.", max_length=50, verbose_name="Numéro d'agrément")),
                ('siret', models.CharField(blank=True, default='', max_length=20, verbose_name='SIRET / Registre commerce')),
                ('description', models.TextField(blank=True, default='', help_text="Présentation libre de l'officine (spécialités, équipe, historique...).", verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.pharmacies.models.logo_upload_path, verbose_name='Logo / Photo')),
                ('services', models.JSONField(blank=True, default=list, help_text='Ex: ["livraison", "urgences", "vaccins", "bebe", "dermatologie"]', verbose_name='Services')),
                ('adresse', models.CharField(max_length=500, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, default='', max_length=10, verbose_name='Code postal')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, default='', verbose_name='Site web')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('localisation', models.BinaryField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'approbation"), ('active', 'Active'), ('suspendue', 'Suspendue')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('est_ouverte', models.BooleanField(default=False, help_text='Mis à jour dynamiquement selon les horaires.', verbose_name='Est ouverte')),
                ('est_de_garde', models.BooleanField(default=False, help_text='Mis à jour dynamiquement selon les périodes de garde.', verbose_name='De garde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['nom'],
            },
        ),
    ]
