# Generated by Django 5.2 on 2026-03-15 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='pharmacien',
            field=models.ForeignKey(limit_choices_to={'role': 'pharmacien'}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacien'),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['statut'], name='idx_pharmacie_statut'),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['ville'], name='idx_pharmacie_ville'),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['est_ouverte'], name='idx_pharmacie_ouverte'),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['est_de_garde'], name='idx_pharmacie_garde'),
        ),
    ]
