# Generated by Django 5.2 on 2026-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionLGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lgo', models.CharField(choices=[('pharmagest', 'Pharmagest'), ('winpharma', 'Winpharma'), ('lgpi', 'LGPI'), ('smart_rx', 'Smart Rx'), ('autre', 'Autre')], max_length=20, verbose_name='Type de LGO')),
                ('version_lgo', models.CharField(blank=True, default='', help_text='Version du LGO détectée sur le poste (ex: 8.2.1).', max_length=50, verbose_name='Version LGO')),
                ('poste_nom', models.CharField(blank=True, default='', help_text='Nom du poste Windows où le LGO est installé.', max_length=100, verbose_name='Nom du poste')),
                ('config', models.JSONField(default=dict, help_text="Générée automatiquement par l'app Desktop. Ne pas modifier manuellement.", verbose_name='Configuration')),
                ('detecte_auto', models.BooleanField(default=False, help_text="True si la config a été générée par l'auto-détection Tauri.", verbose_name='Détecté automatiquement')),
                ('statut', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('erreur', 'En erreur')], default='inactive', max_length=20, verbose_name='Statut')),
                ('derniere_sync', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sync')),
                ('nb_syncs_ok', models.PositiveIntegerField(default=0, verbose_name='Syncs réussies')),
                ('nb_syncs_erreur', models.PositiveIntegerField(default=0, verbose_name='Syncs en erreur')),
                ('derniere_erreur', models.TextField(blank=True, default='', verbose_name='Dernière erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connexion LGO',
                'verbose_name_plural': 'Connexions LGO',
            },
        ),
        migrations.CreateModel(
            name='LogSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sync', models.DateTimeField(auto_now_add=True)),
                ('resultat', models.CharField(choices=[('succes', 'Succès'), ('partiel', 'Partiel (avec erreurs)'), ('echec', 'Échec')], max_length=10)),
                ('declenchement', models.CharField(choices=[('auto', 'Automatique (Celery)'), ('manuel', 'Manuel (pharmacien)'), ('installation', 'Première sync (installation)')], default='auto', max_length=20)),
                ('produits_sync', models.PositiveIntegerField(default=0)),
                ('stocks_sync', models.PositiveIntegerField(default=0)),
                ('prix_sync', models.PositiveIntegerField(default=0)),
                ('duree_secondes', models.FloatField(default=0)),
                ('message_erreur', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Log de synchronisation',
                'verbose_name_plural': 'Logs de synchronisation',
                'ordering': ['-date_sync'],
            },
        ),
    ]
