# Generated by Django 5.2 on 2026-03-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connecteurs_lgo', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connexionlgo',
            name='pharmacie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connexion_lgo', to='pharmacies.pharmacie', verbose_name='Pharmacie'),
        ),
        migrations.AddField(
            model_name='logsync',
            name='connexion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='connecteurs_lgo.connexionlgo', verbose_name='Connexion LGO'),
        ),
        migrations.AddIndex(
            model_name='logsync',
            index=models.Index(fields=['resultat'], name='idx_log_resultat'),
        ),
        migrations.AddIndex(
            model_name='logsync',
            index=models.Index(fields=['declenchement'], name='idx_log_declenchement'),
        ),
    ]
