# Generated by Django 5.2 on 2026-03-15 14:09

import apps.produits.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cip13', models.CharField(blank=True, db_index=True, default='', help_text="Code national d'identification du médicament (13 chiffres).", max_length=13, verbose_name='Code CIP13')),
                ('nom', models.CharField(max_length=500, verbose_name='Nom commercial')),
                ('nom_generique', models.CharField(blank=True, default='', max_length=500, verbose_name='Nom générique (DCI)')),
                ('laboratoire', models.CharField(blank=True, default='', max_length=255, verbose_name='Laboratoire')),
                ('categorie', models.CharField(choices=[('medicament', 'Médicament'), ('parapharmacie', 'Parapharmacie'), ('materiel', 'Matériel médical'), ('autre', 'Autre')], default='medicament', max_length=20, verbose_name='Catégorie')),
                ('forme', models.CharField(blank=True, choices=[('comprimes', 'Comprimés'), ('gelules', 'Gélules'), ('sirop', 'Sirop'), ('injection', 'Injectable'), ('creme', 'Crème / Pommade'), ('gouttes', 'Gouttes'), ('suppositoire', 'Suppositoire'), ('sachet', 'Sachet'), ('spray', 'Spray'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Forme pharmaceutique')),
                ('dosage', models.CharField(blank=True, default='', help_text='Ex: 500mg, 250mg/5ml, 1000UI', max_length=100, verbose_name='Dosage')),
                ('sur_ordonnance', models.BooleanField(default=False, help_text="Si True, un pictogramme dédié s'affiche dans l'app mobile.", verbose_name='Sur ordonnance')),
                ('contre_indications', models.TextField(blank=True, default='', help_text='Principales contre-indications à afficher dans la fiche produit.', verbose_name='Contre-indications')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.produits.models.produit_image_path, verbose_name='Image du produit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['categorie'], name='idx_produit_categorie'), models.Index(fields=['sur_ordonnance'], name='idx_produit_ordonnance'), models.Index(fields=['laboratoire'], name='idx_produit_labo')],
            },
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_fcfa', models.PositiveIntegerField(help_text='Prix de vente TTC en Franc CFA (XOF). Ex: 2500', verbose_name='Prix (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='pharmacies.pharmacie', verbose_name='Pharmacie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Prix',
                'verbose_name_plural': 'Prix',
                'unique_together': {('pharmacie', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('disponible', models.BooleanField(default=True, help_text='False = rupture de stock complète.', verbose_name='Disponible')),
                ('seuil_alerte', models.PositiveIntegerField(default=0, help_text='Alerte envoyée quand quantite <= seuil. 0 = alerte désactivée.', verbose_name="Seuil d'alerte")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacies.pharmacie', verbose_name='Pharmacie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'indexes': [models.Index(fields=['disponible'], name='idx_stock_disponible')],
                'unique_together': {('pharmacie', 'produit')},
            },
        ),
    ]
