# Generated by Django 5.2 on 2026-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='Début de garde')),
                ('date_fin', models.DateTimeField(verbose_name='Fin de garde')),
                ('telephone_garde', models.CharField(blank=True, default='', help_text='Numéro dédié pendant la garde. Si vide, le numéro de la pharmacie est utilisé.', max_length=20, verbose_name='Téléphone de garde')),
                ('zone_ville', models.CharField(blank=True, default='', help_text='Ville ou commune couverte par cette garde.', max_length=100, verbose_name='Ville couverte')),
                ('zone_quartier', models.CharField(blank=True, default='', help_text='Quartier ou zone précise (optionnel).', max_length=100, verbose_name='Quartier / Zone')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('note', models.CharField(blank=True, default='', help_text='Information complémentaire sur cette garde.', max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Période de garde',
                'verbose_name_plural': 'Périodes de garde',
                'ordering': ['date_debut'],
            },
        ),
    ]
