# Generated by Django 5.2 on 2026-03-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardes', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodegarde',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_garde', to='pharmacies.pharmacie', verbose_name='Pharmacie'),
        ),
        migrations.AddIndex(
            model_name='periodegarde',
            index=models.Index(fields=['statut'], name='idx_garde_statut'),
        ),
        migrations.AddIndex(
            model_name='periodegarde',
            index=models.Index(fields=['date_debut'], name='idx_garde_debut'),
        ),
        migrations.AddIndex(
            model_name='periodegarde',
            index=models.Index(fields=['date_fin'], name='idx_garde_fin'),
        ),
        migrations.AddIndex(
            model_name='periodegarde',
            index=models.Index(fields=['zone_ville'], name='idx_garde_ville'),
        ),
    ]
