# Generated by Django 5.2 on 2026-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireExceptionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_ouverture', models.TimeField(blank=True, null=True, verbose_name='Ouverture')),
                ('heure_fermeture', models.TimeField(blank=True, null=True, verbose_name='Fermeture')),
                ('pause_debut', models.TimeField(blank=True, null=True, verbose_name='Début pause midi')),
                ('pause_fin', models.TimeField(blank=True, null=True, verbose_name='Fin pause midi')),
                ('est_ferme', models.BooleanField(default=True, verbose_name='Fermé')),
                ('motif', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif')),
            ],
            options={
                'verbose_name': 'Horaire exceptionnel',
                'verbose_name_plural': 'Horaires exceptionnels',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HoraireSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour')),
                ('heure_ouverture', models.TimeField(blank=True, null=True, verbose_name='Ouverture')),
                ('heure_fermeture', models.TimeField(blank=True, null=True, verbose_name='Fermeture')),
                ('pause_debut', models.TimeField(blank=True, help_text='Laisser vide si ouverture continue.', null=True, verbose_name='Début pause midi')),
                ('pause_fin', models.TimeField(blank=True, help_text='Laisser vide si ouverture continue.', null=True, verbose_name='Fin pause midi')),
                ('est_ferme', models.BooleanField(default=False, verbose_name='Fermé')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horaire semaine',
                'verbose_name_plural': 'Horaires semaine',
                'ordering': ['jour'],
            },
        ),
    ]
