# Generated by Django 5.2 on 2026-03-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horaires', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaireexceptionnel',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_exceptionnels', to='pharmacies.pharmacie', verbose_name='Pharmacie'),
        ),
        migrations.AddField(
            model_name='horairesemaine',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_semaine', to='pharmacies.pharmacie', verbose_name='Pharmacie'),
        ),
        migrations.AlterUniqueTogether(
            name='horaireexceptionnel',
            unique_together={('pharmacie', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='horairesemaine',
            unique_together={('pharmacie', 'jour')},
        ),
    ]
