# Generated by Django 5.2 on 2026-03-15 14:09

import apps.users.managers
import apps.users.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('role', models.CharField(choices=[('public', 'Utilisateur public'), ('pharmacien', 'Pharmacien / Gérant'), ('super_admin', 'Super Administrateur')], default='public', max_length=20, verbose_name='Rôle')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.users.models.avatar_upload_path, verbose_name='Photo de profil')),
                ('ville', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, default='Bénin', max_length=100, verbose_name='Pays')),
                ('numero_licence', models.CharField(blank=True, default='', help_text='Numéro de licence officielle du pharmacien. Obligatoire pour le rôle pharmacien.', max_length=50, verbose_name='Numéro de licence')),
                ('is_approved', models.BooleanField(default=False, help_text='Doit être activé par un super admin pour les comptes pharmacien.', verbose_name='Compte approuvé')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('notif_push', models.BooleanField(default=True, help_text="Recevoir les alertes push sur l'application mobile.", verbose_name='Notifications push')),
                ('notif_email', models.BooleanField(default=True, help_text='Recevoir les alertes par email.', verbose_name='Notifications email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Super admin ayant approuvé ce compte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_approuves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['role'], name='idx_user_role'), models.Index(fields=['is_approved'], name='idx_user_approved')],
            },
            managers=[
                ('objects', apps.users.managers.CustomUserManager()),
            ],
        ),
    ]
